services:
  app:
    build:
      context: .
      target: ${DOCKER_TARGET}
    container_name: petpetlove
    restart: always
    env_file:
      - ${ENV_FILE}
    ports:
      - '5050:5050'
    volumes:
      - .:/app
      - /app/node_modules
    command: ['npm', 'run', '${NODE_ENV}']
